name: Pytest & flake8 control Push

on: push

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Run tests
        run: pytest -v

      - name: Run PEP8 style check
        run: flake8 .
